# Generated by Django 5.0.1 on 2024-02-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_opinion_author_alter_opinion_description_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discounts',
            name='valid_date',
        ),
        migrations.AddField(
            model_name='card',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='card',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='card',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='phone_number',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='card',
            name='postal_code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='card',
            name='street',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='rated',
            field=models.IntegerField(default=0),
        ),
    ]
