# Generated by Django 5.0.1 on 2024-02-07 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounts',
            name='valid_date',
            field=models.DateField(default=datetime.date(2024, 2, 7)),
        ),
    ]
