# Generated by Django 5.0.1 on 2024-02-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_discounts_product_remove_discounts_valid_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=10)),
                ('discount', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=50)),
                ('max_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='promo_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
