# Generated by Django 5.0.1 on 2024-02-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_card_city_alter_card_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_order',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
