# Generated by Django 5.0.1 on 2024-02-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_card_is_order_product_is_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
