# Generated by Django 5.0.1 on 2024-02-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_card_is_delivered_card_is_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
