# Generated by Django 5.0.1 on 2024-02-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_card_is_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('products', models.ManyToManyField(blank=True, default='', to='product.product')),
            ],
        ),
    ]
