# Generated by Django 5.0.1 on 2024-02-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_perfumeoptions_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_options',
            field=models.ManyToManyField(blank=True, default='', to='product.perfumeoptions'),
        ),
    ]
