# Generated by Django 5.0.1 on 2024-02-24 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_product_p_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfumeoptions',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfume_options', to='product.product'),
        ),
    ]
