# Generated by Django 5.0.1 on 2024-02-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_product_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='rated',
        ),
        migrations.AddField(
            model_name='product',
            name='rated',
            field=models.IntegerField(default=0),
        ),
    ]
