# Generated by Django 5.0.1 on 2024-02-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_remove_card_product_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
