# Generated by Django 5.0.1 on 2024-02-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_remove_opinion_rated_product_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rated',
            field=models.IntegerField(default=5),
        ),
    ]
