# Generated by Django 5.0.1 on 2024-02-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_perfumeoptions_item_alter_perfumeoptions_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfumeoptions',
            name='item',
        ),
    ]
