# Generated by Django 5.0.1 on 2024-02-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_remove_perfumeoptions_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='carditem',
            name='size',
            field=models.ManyToManyField(blank=True, default='', to='product.perfumeoptions'),
        ),
    ]
