# Generated by Django 5.0.1 on 2024-02-28 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_carditem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfumeoptions',
            name='product',
        ),
        migrations.AddField(
            model_name='perfumeoptions',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carditem_options', to='product.carditem'),
        ),
    ]
