# Generated by Django 5.0.1 on 2024-02-28 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_remove_perfumeoptions_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfumeoptions',
            name='products',
        ),
        migrations.AddField(
            model_name='perfumeoptions',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfume_options', to='product.product'),
        ),
    ]
