# Generated by Django 5.0.1 on 2024-02-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_remove_perfumeoptions_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carditem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
