# Generated by Django 5.0.1 on 2024-03-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_card_free_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_discoverset',
            field=models.BooleanField(default=False),
        ),
    ]
