# Generated by Django 5.0.1 on 2024-03-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_product_is_discoverset'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
