# Generated by Django 5.0.1 on 2024-03-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_product_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_perfume',
            field=models.BooleanField(default=False),
        ),
    ]
