# Generated by Django 5.0.1 on 2024-03-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_product_is_perfume'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='paczkomat',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
