# Generated by Django 5.0.1 on 2024-03-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_card_is_paczkomat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='phone_number',
            field=models.IntegerField(blank=True, default='', max_length=9),
        ),
    ]
