# Generated by Django 5.0.1 on 2024-03-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_alter_constfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constvalue',
            name='value',
            field=models.CharField(default='', max_length=80),
        ),
    ]
